services:
  web:
    image: nginx:1.27-alpine
    container_name: gansu-radiotelevision-3d-cloud-platform
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "20515:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
